version: '3.9'

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      device: /home/gmehdevi/data/database
      type: volume
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      device: /home/gmehdevi/data/wordpress
      type: volume
      o: bind

networks:
  inception-network:

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: img_nginx
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - inception-network
    ports:
      - "443:443"
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: img_mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - inception-network
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    image: img_wordpress
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - inception-network
    env_file:
      - .env

    restart: unless-stopped